# Generated by Django 5.1.1 on 2024-10-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
    ]
