# Generated by Django 5.1.1 on 2024-10-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cover_image',
            field=models.ImageField(blank=True, default='listing_images/default.png', null=True, upload_to='listing_images/'),
        ),
    ]
